name: Deploy website

on: [push]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Repository Checkout
        uses: actions/checkout@v4

      - name: List directory contents
        run: ls -la
        working-directory: react-map-markers

      - name: Setup NodeJS
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: "yarn"
        working-directory: react-map-markers 

      - name: Install Netlify
        run: npm install netlify-cli@17.10.1 -g
        working-directory: react-map-markers

      - name: Install Dependencies
        run: yarn install --frozen-lockfile
        working-directory: react-map-markers

      - name: Build project
        run: yarn build
        working-directory: react-map-markers

      - name: Deploy to Netlify
        id: netlify_deploy
        run: |
          netlify deploy \
            --dir dist \
            --site ${{ secrets.NETLIFY_SITE_ID }} \
            --auth ${{ secrets.NETLIFY_API_TOKEN }}
        working-directory: react-map-markers
