name: Deploy website

on: [push]

defaults:
  run:
    working-directory: react-map-markers/

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: react-map-markers/

    steps:
      - name: Repository Checkout
        uses: actions/checkout@v4

      - name: List directory contents
        run: ls -la
        working-directory: react-map-markers

      - name: Setup NodeJS
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: "yarn"

      - name: Install Netlify
        run: yarn install netlify-cli@17.10.1 -g

      - name: Install Dependencies
        run: yarn ci

      - name: Build project
        run: yarn build

      - name: Deploy to Netlify
        id: netlify_deploy
        run: |
          netlify deploy \
            --dir dist \
            --site ${{ secrets.NETLIFY_SITE_ID }} \
            --auth ${{ secrets.NETLIFY_API_TOKEN }}
