name: Deploy website

on: [push]

defaults:
  run:
    working-directory: react-map-markers/
env:
  name: 'build'

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [20.x]
    defaults:
      run:
        working-directory: react-map-markers/

    steps:
      - name: Repository Checkout
        uses: actions/checkout@v4

      - uses: actions/cache@v2
        with:
          path: 'react-map-markers/node_modules'
          key: ${{ runner.os }}-yarn-${{ hashFiles('react-map-markers/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-yarn-                
      - name: Install Dependencies (from network)
        if: steps.cache-deps.outputs.cache-hit != 'true'
        run: |
          yarn policies set-version
          yarn install --frozen-lockfile --ignore-optional
      - name: Install Dependencies (from cache)
        if: steps.cache-deps.outputs.cache-hit == 'true'
        run: |
          yarn policies set-version
          yarn install --frozen-lockfile --ignore-optional --offline

      - name: Install Netlify
        run: yarn global add netlify-cli@17.10.1

      - name: Build project
        run: yarn build
        env:
          NEXT_PUBLIC_GOOGLE_MAPS_API_KEY: ${{ secrets.NEXT_PUBLIC_GOOGLE_MAPS_API_KEY }}

      - name: Deploy to Netlify
        id: netlify_deploy
        run: |
          netlify deploy \
            --dir dist \
            --site ${{ secrets.NETLIFY_SITE_ID }} \
            --auth ${{ secrets.NETLIFY_API_TOKEN }}
